version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    environment:
      - PYTHONPATH: src
      - CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run:
          name: Install Python requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install black==19.3b0
      - run:
          name: Run Black
          command: |
            . venv/bin/activate
            black . -l 120
          no_output_timeout: 1m
      - store_test_results:
          path: $CIRCLE_TEST_REPORTS/junit
